language: python
python:
  - "3.5"
sudo: false
env:
  global:
    - PYTHON_VERSION=3.5
install:
  - pip install --upgrade pip coveralls
  - travis_retry pip install .[test]
script:
  - export PLATEMAP_CONFIG=`pwd`/platemap/platemap_config.txt.example
  - platemap make
  - nosetests --with-doctest --with-coverage
  - flake8 --max-complexity 10 platemap setup.py
addons:
  postgresql: "9.3"
services:
  - postgresql
after_success:
  - coveralls
