#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2016--, The Plate Mapper Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------
import click
from platemap.lib.environment import make_database, make_environment


@click.group()
def cli():
    pass


@cli.command()
@click.option('-t', '--test', is_flag=True)
def make(test):
    """Creates the database specified in config"""
    print("Creating database")
    make_database()
    print('Adding schema to database')
    make_environment(test)
    print('Setup finished')

if __name__ == '__main__':
    cli()
